### ISSUE TITLE
NodeJS: Removing dependency on Copilot Labs and replace with Copilot Chat only

### ISSUE THREAD

**Issue by tgrall** [microsoft/CopilotHackathon#23]
Removing dependency on Copilot Labs and replace with Copilot Chat only
```[tasklist]
### Tasks
- [ ] removing copilot labs from dev container
- [ ] review all readme and replace with copilot chat commands
- [x] Data Engineer : nothing to do
- [x] Data Scientist : nothing to do
- [ ] Dot net : replace all Labs by proper chat & inline chat actions
- [ ] Node : replace all Labs by proper chat & inline chat actions
- [x] quarkus : nothing to do
- [x] springboot: nothing todo
```
